### PR TITLE
NLP-186 Make 'tonight' work the same way as 'today'

### PR DESCRIPTION
**Pull request by jonaspok**

### CODE REVIEW

**Review by km1414 — APPROVED** [review]

**Comment by pranas** [comment]
This probably broke some tests, it would be good to see them updated and make sure nothing else broke.

**Comment by jonaspok** [comment]
> This probably broke some tests, it would be good to see them updated and make sure nothing else broke.

Yes, this change made some additional tests broken like '8 tonight' will refer to 8:00 hour instead of 20:00 as it was before. But I think this is a natural consequence of forcing 'tonight' to act as 'today'. Currently I do not see an easy fix for this.

**Comment by pranas** [comment]
Like you commented out `ruleTonight`, it would be good to do the same for the tests + add tonight example next to today examples.

**Comment by jonaspok** [comment]
> Like you commented out `ruleTonight`, it would be good to do the same for the tests + add tonight example next to today examples.

Fixed

**Review by pranas — APPROVED** [review]

**Pull request merged**
